apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cxz9vuw76-python
  janus-idp.io/tekton: cxz9vuw76-python
  backstage.io/kubernetes-id: cxz9vuw76-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cxz9vuw76-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
